# Generated by Django 4.0.5 on 2022-06-08 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitors',
            old_name='company',
            new_name='company_name',
        ),
    ]
