# Generated by Django 4.0.5 on 2022-06-08 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_rename_name_visitors_visitor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitors',
            old_name='inteviewer',
            new_name='interviewer',
        ),
    ]
