# Generated by Django 4.0.5 on 2022-06-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_rename_inteviewer_visitors_interviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='accompany1_name',
            field=models.CharField(max_length=25, null=True, verbose_name='同行者1お名前'),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='accompany2_name',
            field=models.CharField(max_length=25, null=True, verbose_name='同行者2お名前'),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='accompany3_name',
            field=models.CharField(max_length=25, null=True, verbose_name='同行者3お名前'),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='company_name',
            field=models.CharField(max_length=50, null=True, verbose_name='会社名'),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='interviewer',
            field=models.CharField(max_length=25, null=True, verbose_name='担当者'),
        ),
    ]
