# Generated by Django 4.0.5 on 2022-06-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_alter_visitors_accompany1_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='accompany1_temp',
            field=models.FloatField(null=True, verbose_name='同行者1検温'),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='accompany2_temp',
            field=models.FloatField(null=True, verbose_name='同行者2検温'),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='accompany3_temp',
            field=models.FloatField(null=True, verbose_name='同行者3検温'),
        ),
    ]
