# Generated by Django 4.0.5 on 2022-06-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_alter_visitors_accompany1_temp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'コンタクト履歴', 'verbose_name_plural': 'コンタクト履歴'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': '社員メンバー', 'verbose_name_plural': '社員メンバー'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '役職', 'verbose_name_plural': '役職'},
        ),
        migrations.AlterModelOptions(
            name='visitors',
            options={'verbose_name': '来訪者履歴', 'verbose_name_plural': '来訪者履歴'},
        ),
        migrations.AddField(
            model_name='visitors',
            name='position',
            field=models.CharField(max_length=25, null=True, verbose_name='役職'),
        ),
    ]
