# Generated by Django 4.0.5 on 2022-06-08 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0007_alter_contact_options_alter_member_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='post',
        ),
    ]
