# Generated by Django 4.0.5 on 2022-06-08 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0008_remove_member_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.post'),
        ),
    ]
