# Generated by Django 4.0.5 on 2022-06-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0009_member_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='is_contacted',
            field=models.BooleanField(default=False, help_text='コンタクトしたらTrue'),
        ),
    ]
