# Generated by Django 4.0.5 on 2022-06-09 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0010_visitors_is_contacted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='inteviewer',
            new_name='interviewer',
        ),
    ]
