# Generated by Django 4.0.5 on 2022-06-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0011_rename_inteviewer_contact_interviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='accompany1_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='同行者1お名前'),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='accompany1_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='同行者1検温'),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='accompany2_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='同行者2お名前'),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='accompany2_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='同行者2検温'),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='accompany3_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='同行者3お名前'),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='accompany3_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='同行者3検温'),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='会社名'),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='interviewer',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='担当者'),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='position',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='役職'),
        ),
    ]
