# Generated by Django 4.0.5 on 2022-06-10 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0012_alter_visitors_accompany1_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='interviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.member', verbose_name='担当者'),
        ),
    ]
