# Generated by Django 3.2 on 2022-06-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0013_alter_contact_interviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='ご用件'),
        ),
    ]
