# Generated by Django 3.2 on 2022-06-12 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0014_alter_visitors_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contents',
            field=models.TextField(blank=True, null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.member', verbose_name='担当者'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='退室時刻'),
        ),
    ]
