# Generated by Django 3.2 on 2022-06-12 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0015_auto_20220612_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='氏名'),
        ),
        migrations.AlterField(
            model_name='member',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.post'),
        ),
    ]
